pipeline:
  name: Java-calculator
  identifier: Javacalculator
  projectIdentifier: U101
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ashravank
        repoName: Java-calculator
        build: <+input>
  stages:
    - stage:
        name: Build-Test
        identifier: BuildTest
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec: {}
